// packages/tanstack-start/src/client/OptionsContext.tsx
import React from 'react';

import type { TanstackStartClerkProviderProps as ClerkProviderProps } from './types';

type ClerkContextValue = Partial<Omit<ClerkProviderProps, 'children'>>;

const ClerkOptionsCtx = React.createContext<{ value: ClerkContextValue } | undefined>(undefined);
ClerkOptionsCtx.displayName = 'ClerkOptionsCtx';

const useClerkOptions = (): ClerkContextValue => {
  const ctx = React.useContext(ClerkOptionsCtx) as { value: ClerkContextValue };
  return ctx.value;
};

const ClerkOptionsProvider = (props: React.PropsWithChildren<{ options: ClerkContextValue }>) => {
  const { children, options } = props;
  return <ClerkOptionsCtx.Provider value={{ value: options }}>{children}</ClerkOptionsCtx.Provider>;
};

export { ClerkOptionsProvider, useClerkOptions };

// packages/tanstack-solid-start/src/client/OptionsContext.tsx
import type { JSXElement } from 'solid-js';
import { createContext, useContext } from 'solid-js';

import type { TanstackStartClerkProviderProps as ClerkProviderProps } from './types';

type ClerkContextValue = Partial<Omit<ClerkProviderProps, 'children'>>;

const ClerkOptionsCtx = createContext<{ value: ClerkContextValue } | undefined>(undefined);

const useClerkOptions = (): ClerkContextValue => {
  const ctx = useContext(ClerkOptionsCtx);
  return ctx?.value ?? {};
};

const ClerkOptionsProvider = (props: { children: JSXElement; options: ClerkContextValue }) => {
  const { children, options } = props;
  return <ClerkOptionsCtx.Provider value={{ value: options }}>{children}</ClerkOptionsCtx.Provider>;
};

export { ClerkOptionsProvider, useClerkOptions };
