// playground/composed/src/main.tsx
import { ClerkProvider } from '@clerk/react';
import { ui } from '@clerk/ui';
import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';

import { App } from './App';

const publishableKey = import.meta.env.VITE_CLERK_PUBLISHABLE_KEY;

if (!publishableKey) {
  throw new Error('Missing VITE_CLERK_PUBLISHABLE_KEY in .env.local');
}

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <ClerkProvider
      publishableKey={publishableKey}
      ui={ui}
    >
      <App />
    </ClerkProvider>
  </StrictMode>,
);

// playground/solid/src/index.tsx
/* @refresh reload */
import { render } from 'solid-js/web';

import './index.css';
import App from './App';
import { ClerkProvider } from '@clerk/clerk-solid';
const root = document.getElementById('root');

const pkKey = import.meta.env['VITE_CLERK_PUBLISHABLE_KEY'] as string;

if (import.meta.env.DEV && !(root instanceof HTMLElement)) {
  throw new Error(
    'Root element not found. Did you forget to add it to your index.html? Or maybe the id attribute got mispelled?',
  );
}

render(
  () => (
    <ClerkProvider publishableKey={pkKey}>
      <App />,
    </ClerkProvider>
  ),
  root!,
);
