// packages/solid/src/contexts/StructureContext.tsx
import { type ParentComponent, createContext, useContext } from 'solid-js';

import { assertWrappedByClerkProvider } from './assertHelpers';

export interface StructureContextValue {
  guaranteedLoaded: boolean;
}

export const StructureContextStates = Object.freeze({
  noGuarantees: Object.freeze({
    guaranteedLoaded: false,
  }),
  guaranteedLoaded: Object.freeze({
    guaranteedLoaded: true,
  }),
});

export const StructureContext = createContext<StructureContextValue | undefined>(undefined);

// @ts-expect-error hack
StructureContext.displayName = 'StructureContext';

const useStructureContext = (): StructureContextValue => {
  const structureCtx = useContext(StructureContext);
  assertWrappedByClerkProvider(structureCtx);
  return structureCtx;
};

export const LoadedGuarantee: ParentComponent = props => {
  const structure = useStructureContext();
  if (structure.guaranteedLoaded) {
    return <>{props.children}</>;
  }
  return (
    <StructureContext.Provider value={StructureContextStates.guaranteedLoaded}>
      {props.children}
    </StructureContext.Provider>
  );
};

// packages/react/src/contexts/StructureContext.tsx
import React from 'react';

import { assertWrappedByClerkProvider } from './assertHelpers';

export interface StructureContextValue {
  guaranteedLoaded: boolean;
}

export const StructureContextStates = Object.freeze({
  noGuarantees: Object.freeze({
    guaranteedLoaded: false,
  }),
  guaranteedLoaded: Object.freeze({
    guaranteedLoaded: true,
  }),
});

export const StructureContext = React.createContext<StructureContextValue | undefined>(undefined);

StructureContext.displayName = 'StructureContext';

const useStructureContext = (): StructureContextValue => {
  const structureCtx = React.useContext(StructureContext);
  assertWrappedByClerkProvider(structureCtx);
  return structureCtx;
};

export const LoadedGuarantee: React.FC = ({ children }) => {
  const structure = useStructureContext();
  if (structure.guaranteedLoaded) {
    return <>{children}</>;
  }
  return (
    <StructureContext.Provider value={StructureContextStates.guaranteedLoaded}>{children}</StructureContext.Provider>
  );
};
