// playground/solid/src/index.tsx
/* @refresh reload */
import { render } from 'solid-js/web';

import './index.css';
import App from './App';
import { ClerkProvider } from '@clerk/clerk-solid';
const root = document.getElementById('root');

const pkKey = import.meta.env['VITE_CLERK_PUBLISHABLE_KEY'] as string;

if (import.meta.env.DEV && !(root instanceof HTMLElement)) {
  throw new Error(
    'Root element not found. Did you forget to add it to your index.html? Or maybe the id attribute got mispelled?',
  );
}

render(
  () => (
    <ClerkProvider publishableKey={pkKey}>
      <App />,
    </ClerkProvider>
  ),
  root!,
);

// integration/templates/react-router-library/src/main.tsx
import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter, Routes, Route } from 'react-router';
import { ClerkProvider } from '@clerk/react-router';
import './index.css';
import App from './App.tsx';

const PUBLISHABLE_KEY = import.meta.env.VITE_CLERK_PUBLISHABLE_KEY;

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <BrowserRouter>
      <ClerkProvider publishableKey={PUBLISHABLE_KEY}>
        <Routes>
          <Route
            path='/'
            element={<App />}
          />
        </Routes>
      </ClerkProvider>
    </BrowserRouter>
  </StrictMode>,
);
