// packages/vue/src/components/SignOutButton.vue
<script setup lang="ts">
import { useAttrs, useSlots } from 'vue';
import type { SignOutOptions } from '@clerk/types';
import { useClerk } from '../composables/useClerk';
import { assertSingleChild, normalizeWithDefaultValue } from '../utils';

interface SignOutButtonProps {
  signOutOptions?: SignOutOptions;
  sessionId?: string;
  redirectUrl?: string;
}

const props = defineProps<SignOutButtonProps>();

const clerk = useClerk();
const slots = useSlots();
const attrs = useAttrs();

function getChildComponent() {
  const children = normalizeWithDefaultValue(slots.default?.({}), 'Sign out');
  return assertSingleChild(children, 'SignOutButton');
}

function clickHandler() {
  const signOutOptions: SignOutOptions = {
    redirectUrl: props.signOutOptions?.redirectUrl ?? props.redirectUrl,
    sessionId: props.signOutOptions?.sessionId ?? props.sessionId,
  };
  void clerk.value?.signOut(signOutOptions);
}
</script>

<template>
  <component
    :is="getChildComponent"
    v-bind="attrs"
    @click="clickHandler"
  >
    <slot />
  </component>
</template>

// packages/astro/src/client/react/SignOutButton.tsx
import type { SignOutOptions } from '@clerk/types';
import React from 'react';

import type { WithClerkProp } from './utils';
import { assertSingleChild, normalizeWithDefaultValue, safeExecute, withClerk } from './utils';

export type SignOutButtonProps = SignOutOptions & {
  children?: React.ReactNode;
};

export const SignOutButton = withClerk(
  ({ clerk, children, ...props }: React.PropsWithChildren<WithClerkProp<SignOutButtonProps>>) => {
    const { redirectUrl = '/', sessionId, ...rest } = props;

    children = normalizeWithDefaultValue(children, 'Sign out');
    const child = assertSingleChild(children)('SignOutButton');

    const clickHandler = () => clerk?.signOut({ redirectUrl, sessionId });
    const wrappedChildClickHandler: React.MouseEventHandler = async e => {
      await safeExecute((child as any).props.onClick)(e);
      return clickHandler();
    };

    const childProps = { ...rest, onClick: wrappedChildClickHandler };
    return React.cloneElement(child as React.ReactElement<unknown>, childProps);
  },
  'SignOutButton',
);
