// packages/tanstack-solid-start/src/client/useAwaitableNavigate.ts
import type { NavigateOptions } from '@tanstack/solid-router';
import { useLocation, useNavigate } from '@tanstack/solid-router';
import { createEffect, useTransition } from 'solid-js';

type Resolve = (value?: unknown) => void;

export const useAwaitableNavigate = () => {
  const navigate = useNavigate();
  const location = useLocation();
  const resolveFunctionsRef: Resolve[] = [];
  const resolveAll = () => {
    resolveFunctionsRef.forEach(resolve => resolve());
    resolveFunctionsRef.splice(0, resolveFunctionsRef.length);
  };
  const [_, startTransition] = useTransition();

  createEffect(() => {
    location();
    resolveAll();
  });

  return (options: NavigateOptions) => {
    return new Promise(res => {
      startTransition(() => {
        resolveFunctionsRef.push(res);
        res(navigate(options));
      });
    });
  };
};

// packages/react-router/src/client/useAwaitableNavigate.tsx
import React from 'react';
import type { NavigateOptions } from 'react-router';
import { useLocation, useNavigate } from 'react-router';

type Resolve = (value?: unknown) => void;

export const useAwaitableNavigate = () => {
  const navigate = useNavigate();
  const location = useLocation();

  const resolveFunctionsRef = React.useRef<Resolve[]>([]);
  const resolveAll = () => {
    resolveFunctionsRef.current.forEach(resolve => resolve());
    resolveFunctionsRef.current.splice(0, resolveFunctionsRef.current.length);
  };

  // location.key will change even when navigating to the same url,
  // so we will successfully resolve in that case as well
  React.useEffect(() => {
    resolveAll();
  }, [location]);

  return (to: string, opts?: NavigateOptions) => {
    return new Promise(res => {
      resolveFunctionsRef.current.push(res);
      navigate(to, opts);
    });
  };
};
