// packages/tanstack-solid-start/src/client/useAwaitableNavigate.ts
import type { NavigateOptions } from '@tanstack/solid-router';
import { useLocation, useNavigate } from '@tanstack/solid-router';
import { createEffect, useTransition } from 'solid-js';

type Resolve = (value?: unknown) => void;

export const useAwaitableNavigate = () => {
  const navigate = useNavigate();
  const location = useLocation();
  const resolveFunctionsRef: Resolve[] = [];
  const resolveAll = () => {
    resolveFunctionsRef.forEach(resolve => resolve());
    resolveFunctionsRef.splice(0, resolveFunctionsRef.length);
  };
  const [_, startTransition] = useTransition();

  createEffect(() => {
    location();
    resolveAll();
  });

  return (options: NavigateOptions) => {
    return new Promise(res => {
      startTransition(() => {
        resolveFunctionsRef.push(res);
        res(navigate(options));
      });
    });
  };
};

// packages/remix/src/client/useAwaitableNavigate.tsx
import { useNavigate, useTransition } from '@remix-run/react';
import React from 'react';

type Resolve = (value?: unknown) => void;

export const useAwaitableNavigate = () => {
  const navigate = useNavigate();
  const transition = useTransition();
  const resolveFunctionsRef = React.useRef<Resolve[]>([]);

  const resolveAll = () => {
    if (transition.state !== 'idle') {
      return;
    }
    resolveFunctionsRef.current.forEach(resolve => resolve());
    resolveFunctionsRef.current.splice(0, resolveFunctionsRef.current.length);
  };

  React.useEffect(() => {
    resolveAll();
  }, [transition.state]);

  return (to: string) => {
    return new Promise(res => {
      resolveFunctionsRef.current.push(res);
      navigate(to);
    });
  };
};
