// packages/astro/src/react/SignInWithMetamaskButton.tsx
import type { RedirectUrlProp } from '@clerk/types';
import React from 'react';

import type { WithClerkProp } from './utils';
import { assertSingleChild, normalizeWithDefaultValue, safeExecute, withClerk } from './utils';

export type SignInWithMetamaskButtonProps = RedirectUrlProp & {
  children?: React.ReactNode;
};

export const SignInWithMetamaskButton = withClerk(
  ({ clerk, children, ...props }: React.PropsWithChildren<WithClerkProp<SignInWithMetamaskButtonProps>>) => {
    const { redirectUrl, ...rest } = props;

    children = normalizeWithDefaultValue(children, 'Sign in with Metamask');
    const child = assertSingleChild(children)('SignInWithMetamaskButton');

    const clickHandler = () => {
      if (!clerk) {
        return;
      }
      return clerk.authenticateWithMetamask({ redirectUrl: redirectUrl || undefined });
    };

    const wrappedChildClickHandler: React.MouseEventHandler = async e => {
      await safeExecute((child as any).props.onClick)(e);
      return clickHandler();
    };

    const childProps = { ...rest, onClick: wrappedChildClickHandler };
    return React.cloneElement(child as React.ReactElement<unknown>, childProps);
  },
  'SignInWithMetamaskButton',
);

// packages/vue/src/components/SignInWithMetamaskButton.vue
<script setup lang="ts">
import { useAttrs, useSlots } from 'vue';
import type { RedirectUrlProp } from '@clerk/types';
import { useClerk } from '../composables/useClerk';
import { assertSingleChild, normalizeWithDefaultValue } from '../utils';

type Props = RedirectUrlProp & {
mode?: 'modal' | 'redirect';
}

const props = defineProps<Props>();

const clerk = useClerk();
const slots = useSlots();
const attrs = useAttrs();

function getChildComponent() {
  const children = normalizeWithDefaultValue(slots.default?.({}), 'Sign in with Metamask');
  return assertSingleChild(children, 'SignInWithMetamaskButton');
}

function clickHandler() {
    void clerk.value?.authenticateWithMetamask({ redirectUrl: props.redirectUrl || undefined });
}
</script>

<template>
  <component
    :is="getChildComponent"
    v-bind="attrs"
    @click="clickHandler"
  >
    <slot />
  </component>
</template>
