// packages/astro/src/react/SubscriptionDetailsButton.tsx
import type { __experimental_SubscriptionDetailsButtonProps } from '@clerk/types';
import React from 'react';

import type { WithClerkProp } from './utils';
import { assertSingleChild, normalizeWithDefaultValue, safeExecute, withClerk } from './utils';
import { mergePortalProps, normalizePortalRoot } from './portalProps';

export type { __experimental_SubscriptionDetailsButtonProps as SubscriptionDetailsButtonProps };

export const SubscriptionDetailsButton = withClerk(
  ({
    clerk,
    children,
    ...props
  }: WithClerkProp<React.PropsWithChildren<__experimental_SubscriptionDetailsButtonProps>>) => {
    const { for: _for, subscriptionDetailsProps, onSubscriptionCancel, ...rest } = props;
    children = normalizeWithDefaultValue(children, 'Subscription details');
    const child = assertSingleChild(children)('SubscriptionDetailsButton');

    // Note: Auth checks are moved to runtime since Astro React components
    // don't have access to auth context at render time like Vue/React apps do

    const clickHandler = () => {
      if (!clerk) {
        return;
      }

      // Merge portal config: top-level props take precedence over nested subscriptionDetailsProps
      // Note: subscriptionDetailsProps.portalRoot is PortalRoot (HTMLElement | null | undefined) which is
      // incompatible with PortalProps.portalRoot, so we handle portalRoot separately
      const topLevelPortalConfig = mergePortalProps(props);

      // Get portalRoot from top-level props first, then fallback to subscriptionDetailsProps
      const portalRootValue = topLevelPortalConfig.portalRoot
        ? normalizePortalRoot(topLevelPortalConfig.portalRoot)
        : (subscriptionDetailsProps?.portalRoot ?? undefined);

      return clerk.__internal_openSubscriptionDetails({
        for: _for,
        onSubscriptionCancel,
        ...subscriptionDetailsProps,
        portalId: topLevelPortalConfig.portalId ?? subscriptionDetailsProps?.portalId,
        portalRoot: portalRootValue,
      });
    };

    const wrappedChildClickHandler: React.MouseEventHandler = e => {
      if (child && typeof child === 'object' && 'props' in child) {
        void safeExecute(child.props.onClick)(e);
      }
      return clickHandler();
    };

    const childProps = { ...rest, onClick: wrappedChildClickHandler };
    return React.cloneElement(child as React.ReactElement<unknown>, childProps);
  },
  'SubscriptionDetailsButton',
);

// packages/vue/src/components/SubscriptionDetailsButton.vue
<script setup lang="ts">
import { useAttrs, useSlots } from 'vue';
import type { __experimental_SubscriptionDetailsButtonProps } from '@clerk/shared/types';
import { useClerk } from '../composables/useClerk';
import { useAuth } from '../composables/useAuth';
import { assertSingleChild, mergePortalProps, normalizePortalRoot, normalizeWithDefaultValue } from '../utils';

type SubscriptionDetailsButtonProps = Omit<__experimental_SubscriptionDetailsButtonProps, 'onSubscriptionCancel'>;
const props = defineProps<SubscriptionDetailsButtonProps>();

const clerk = useClerk();
const { userId, orgId } = useAuth();
const slots = useSlots();
const attrs = useAttrs();

// Authentication checks - similar to React implementation
if (userId.value === null) {
  throw new Error('Ensure that `<SubscriptionDetailsButton />` is rendered inside a `<SignedIn />` component.');
}

if (orgId.value === null && props.for === 'organization') {
  throw new Error('Wrap `<SubscriptionDetailsButton for="organization" />` with a check for an active organization.');
}

function getChildComponent() {
  const children = normalizeWithDefaultValue(slots.default?.({}), 'Subscription details');
  return assertSingleChild(children, 'SubscriptionDetailsButton');
}

const emit = defineEmits<{ (e: 'subscription-cancel'): void }>();

function clickHandler() {
  if (!clerk.value) {
    return;
  }

  // Merge portal config: top-level props take precedence over nested subscriptionDetailsProps
  // Note: subscriptionDetailsProps.portalRoot is PortalRoot (HTMLElement | null | undefined) which is
  // incompatible with PortalProps.portalRoot, so we handle portalRoot separately
  const topLevelPortalConfig = mergePortalProps(props);

  // Get portalRoot from top-level props first, then fallback to subscriptionDetailsProps
  const portalRootValue = topLevelPortalConfig.portalRoot
    ? normalizePortalRoot(topLevelPortalConfig.portalRoot)
    : (props.subscriptionDetailsProps?.portalRoot ?? undefined);

  return clerk.value.__internal_openSubscriptionDetails({
    for: props.for,
    ...props.subscriptionDetailsProps,
    portalId: topLevelPortalConfig.portalId ?? props.subscriptionDetailsProps?.portalId,
    portalRoot: portalRootValue,
    onSubscriptionCancel: () => emit('subscription-cancel'),
  });
}
</script>

<template>
  <component
    :is="getChildComponent"
    v-bind="attrs"
    @click="clickHandler"
  >
    <slot />
  </component>
</template>
