// packages/shared/src/react/ClerkContextProvider.tsx
import React from 'react';

import type { Clerk, LoadedClerk, Resources } from '../types';
import {
  __experimental_CheckoutProvider as CheckoutProvider,
  ClerkInstanceContext,
  ClientContext,
  OrganizationProvider,
  SessionContext,
  UserContext,
} from './contexts';
import { assertClerkSingletonExists } from './utils';

type ClerkContextProps = {
  clerk: Clerk;
  children: React.ReactNode;
  swrConfig?: any;
};

type CoreClerkContextProviderState = Resources;

export function ClerkContextProvider(props: ClerkContextProps): JSX.Element | null {
  const clerk = props.clerk as LoadedClerk;

  assertClerkSingletonExists(clerk);

  const [state, setState] = React.useState<CoreClerkContextProviderState>({
    client: clerk.client,
    session: clerk.session,
    user: clerk.user,
    organization: clerk.organization,
  });

  React.useEffect(() => {
    return clerk.addListener(e => setState({ ...e }));
  }, []);

  const { client, session, user, organization } = state;
  const clerkCtx = React.useMemo(() => ({ value: clerk }), []);
  const clientCtx = React.useMemo(() => ({ value: client }), [client]);
  const sessionCtx = React.useMemo(() => ({ value: session }), [session]);
  const userCtx = React.useMemo(() => ({ value: user }), [user]);
  const organizationCtx = React.useMemo(
    () => ({
      value: { organization: organization },
    }),
    [organization],
  );

  return (
    <ClerkInstanceContext.Provider value={clerkCtx}>
      <ClientContext.Provider value={clientCtx}>
        <SessionContext.Provider value={sessionCtx}>
          <OrganizationProvider
            {...organizationCtx.value}
            swrConfig={props.swrConfig}
          >
            <UserContext.Provider value={userCtx}>
              <CheckoutProvider
                // @ts-expect-error - value is not used
                value={undefined}
              >
                {props.children}
              </CheckoutProvider>
            </UserContext.Provider>
          </OrganizationProvider>
        </SessionContext.Provider>
      </ClientContext.Provider>
    </ClerkInstanceContext.Provider>
  );
}

// packages/solid/src/contexts/ClerkContextProvider.tsx
import type { ClientResource, InitialState, Resources } from '@clerk/types';
import type { Accessor, ParentComponent } from 'solid-js';
import { createEffect, createSignal, on, onCleanup, onMount } from 'solid-js';

import IsomorphicClerk from '../isomorphicClerk';
import type { IsomorphicClerkOptions } from '../types';
import { deriveState } from '../utils/deriveState';
import { AuthContext } from './AuthContext';
import { ClientContext } from './ClientContext';
import { IsomorphicClerkContext } from './IsomorphicClerkContext';
import { OrganizationContext } from './OrganizationContext';
import { SessionContext } from './SessionContext';
import { UserContext } from './UserContext';

type ClerkContextProvider = {
  isomorphicClerkOptions: IsomorphicClerkOptions;
  initialState: InitialState | undefined;
};

export type ClerkContextProviderState = Resources;

export const ClerkContextProvider: ParentComponent<ClerkContextProvider> = props => {
  const { isomorphicClerkOptions, initialState } = props;
  const thisClerk = createLoadedIsomorphicClerk(isomorphicClerkOptions);

  const [state, setState] = createSignal<ClerkContextProviderState>({
    client: thisClerk.isomorphicClerk().client as ClientResource,
    session: thisClerk.isomorphicClerk().session,
    user: thisClerk.isomorphicClerk().user,
    organization: thisClerk.isomorphicClerk().organization,
    lastOrganizationInvitation: null,
    lastOrganizationMember: null,
  });

  createEffect(() => {
    const unsub = thisClerk.isomorphicClerk().addListener(e => setState({ ...e }));
    if (typeof unsub === 'function') {
      onCleanup(unsub);
    }
  });

  const derivedState = () => deriveState(thisClerk.loaded(), state(), initialState);
  const clerkCtx = () => ({
    clerkLoaded: thisClerk.loaded(),
    value: thisClerk.isomorphicClerk(),
  });

  const clientCtx = () => ({
    value: state().client,
  });

  const userCtx = () => ({ value: state().user });
  const sessionCtx = () => ({ value: state().session });
  const organizationCtx = () => ({
    value: {
      organization: state().organization,
      lastOrganizationInvitation: state().lastOrganizationInvitation,
      lastOrganizationMember: state().lastOrganizationMember,
    },
  });

  return (
    // @ts-expect-error its fine
    <IsomorphicClerkContext.Provider value={clerkCtx}>
      <ClientContext.Provider value={clientCtx}>
        <SessionContext.Provider value={sessionCtx}>
          <OrganizationContext.Provider value={organizationCtx}>
            <AuthContext.Provider
              value={() => ({
                value: derivedState(),
              })}
            >
              <UserContext.Provider value={userCtx}>{props.children}</UserContext.Provider>
            </AuthContext.Provider>
          </OrganizationContext.Provider>
        </SessionContext.Provider>
      </ClientContext.Provider>
    </IsomorphicClerkContext.Provider>
  );
};

const createLoadedIsomorphicClerk = (_options: IsomorphicClerkOptions | Accessor<IsomorphicClerkOptions>) => {
  const [loaded, setLoaded] = createSignal(false);
  const options = () => (typeof _options === 'function' ? _options() : _options);
  const isomorphicClerk = () => IsomorphicClerk.getOrCreateInstance(options());

  createEffect(
    on(
      () => options().appearance,
      () => {
        isomorphicClerk().__unstable__updateProps({ appearance: options().appearance });
      },
    ),
  );

  createEffect(
    on(
      () => options().localization,
      () => {
        isomorphicClerk().__unstable__updateProps({ options: options() });
      },
    ),
  );

  onMount(() => {
    isomorphicClerk().addOnLoaded(() => setLoaded(true));
  });

  return { isomorphicClerk, loaded };
};
