// integration/templates/vue-vite/src/views/billing/CheckoutBtn.vue
<template>
  <main>
    <Show when="signed-in">
      <CheckoutButton
        planId="cplan_2wMjqdlza0hTJc4HLCoBwAiExhF"
        planPeriod="month"
      >
        Checkout Now
      </CheckoutButton>
    </Show>
  </main>
</template>

<script setup lang="ts">
import { Show } from '@clerk/vue';
import { CheckoutButton } from '@clerk/vue/experimental';
</script>

// integration/templates/next-app-router/src/app/billing/checkout-btn/page.tsx
import { Show } from '@clerk/nextjs';
import { CheckoutButton } from '@clerk/nextjs/experimental';

export default function Home() {
  return (
    <main>
      <Show when='signed-in'>
        <CheckoutButton
          planId='cplan_2wMjqdlza0hTJc4HLCoBwAiExhF'
          planPeriod='month'
        >
          Checkout Now
        </CheckoutButton>
      </Show>
    </main>
  );
}
