// integration/templates/vue-vite/src/views/PricingTable.vue
<script setup lang="ts">
import { PricingTable } from '@clerk/vue';
import { useRoute } from 'vue-router';

const route = useRoute();
const newSubscriptionRedirectUrl = route.query.newSubscriptionRedirectUrl as string;
</script>

<template>
  <PricingTable :newSubscriptionRedirectUrl="newSubscriptionRedirectUrl" />
</template>

// integration/templates/next-app-router/src/app/pricing-table/page.tsx
import { PricingTable } from '@clerk/nextjs';

export default async function PricingTablePage({
  searchParams,
}: {
  searchParams: Promise<{ newSubscriptionRedirectUrl: string }>;
}) {
  const newSubscriptionRedirectUrl = (await searchParams).newSubscriptionRedirectUrl;
  return <PricingTable newSubscriptionRedirectUrl={newSubscriptionRedirectUrl} />;
}
