// playground/solid/src/index.tsx
/* @refresh reload */
import { render } from 'solid-js/web';

import './index.css';
import App from './App';
import { ClerkProvider } from '@clerk/clerk-solid';
const root = document.getElementById('root');

const pkKey = import.meta.env['VITE_CLERK_PUBLISHABLE_KEY'] as string;

if (import.meta.env.DEV && !(root instanceof HTMLElement)) {
  throw new Error(
    'Root element not found. Did you forget to add it to your index.html? Or maybe the id attribute got mispelled?',
  );
}

render(
  () => (
    <ClerkProvider publishableKey={pkKey}>
      <App />,
    </ClerkProvider>
  ),
  root!,
);

// integration/templates/react-cra/src/index.tsx
import React from 'react';
import ReactDOM from 'react-dom/client';
import './index.css';
import App from './App';
import { ClerkProvider } from '@clerk/clerk-react';

const root = ReactDOM.createRoot(document.getElementById('root') as HTMLElement);
root.render(
  <React.StrictMode>
    <ClerkProvider publishableKey={process.env.REACT_APP_CLERK_PUBLISHABLE_KEY as string}>
      <App />
    </ClerkProvider>
  </React.StrictMode>,
);
