// integration/templates/vue-vite/src/components/CustomUserButton.vue
<script setup lang="ts">
import { UserButton } from '@clerk/vue';
import { ref } from 'vue';

const isActionClicked = ref(false);
</script>

<template>
  <UserButton>
    <UserButton.MenuItems>
      <UserButton.Action label="signOut" />
      <UserButton.Action label="manageAccount" />
      <UserButton.Link
        label="Custom link"
        href="/profile"
      >
        <template #labelIcon>
          <div>Icon</div>
        </template>
      </UserButton.Link>
      <UserButton.Action
        label="Custom page"
        open="terms"
      >
        <template #labelIcon>
          <div>Icon</div>
        </template>
      </UserButton.Action>
      <UserButton.Action
        label="Custom action"
        @click="isActionClicked = true"
      >
        <template #labelIcon>
          <div>Icon</div>
        </template>
      </UserButton.Action>
    </UserButton.MenuItems>
    <UserButton.UserProfilePage
      label="Terms"
      url="terms"
    >
      <template #labelIcon>
        <div>Icon</div>
      </template>
      <div>
        <h1>Custom Terms Page</h1>
        <p>This is the custom terms page</p>
      </div>
    </UserButton.UserProfilePage>
    <UserButton.UserProfileLink
      label="Homepage"
      url="/"
    >
      <template #labelIcon>
        <div>Icon</div>
      </template>
    </UserButton.UserProfileLink>
  </UserButton>
  <div>Is action clicked: {{ isActionClicked }}</div>
</template>

// integration/templates/react-vite/src/custom-user-button/index.tsx
import { UserButton } from '@clerk/clerk-react';
import { useContext } from 'react';
import { PageContext, PageContextProvider } from '../PageContext.tsx';

function Page1() {
  const { counter, setCounter } = useContext(PageContext);

  return (
    <>
      <h1 data-page={1}>Page 1</h1>
      <p data-page={1}>Counter: {counter}</p>
      <button
        data-page={1}
        onClick={() => setCounter(a => a + 1)}
      >
        Update
      </button>
    </>
  );
}

export default function Page() {
  return (
    <PageContextProvider>
      <UserButton>
        <UserButton.UserProfilePage
          label={'Page 1'}
          labelIcon={<p data-label-icon={'page-1'}>🙃</p>}
          url='page-1'
        >
          <Page1 />
        </UserButton.UserProfilePage>
        <UserButton.UserProfilePage label={'security'} />
        <UserButton.UserProfilePage
          label={'Page 2'}
          labelIcon={<p data-label-icon={'page-2'}>🙃</p>}
          url='page-2'
        >
          <h1>Page 2</h1>
        </UserButton.UserProfilePage>
        🌐
        <UserButton.UserProfileLink
          url={'https://clerk.com'}
          label={'Visit Clerk'}
          labelIcon={<p data-label-icon={'page-3'}>🌐</p>}
        />
        <UserButton.MenuItems>
          <UserButton.Action
            label={'page-1'}
            labelIcon={<span>🙃</span>}
            open={'page-1'}
          />
          <UserButton.Action label={'manageAccount'} />
          <UserButton.Action label={'signOut'} />
          <UserButton.Link
            href={'http://clerk.com'}
            label={'Visit Clerk'}
            labelIcon={<span>🌐</span>}
          />

          <UserButton.Link
            href={'/user'}
            label={'Visit User page'}
            labelIcon={<span>🌐</span>}
          />

          <UserButton.Action
            label={'Custom Alert'}
            labelIcon={<span>🔔</span>}
            onClick={() => alert('custom-alert')}
          />
        </UserButton.MenuItems>
        <UserButton.UserProfileLink
          url={'/user'}
          label={'Visit User page'}
          labelIcon={<p data-label-icon={'page-4'}>🌐</p>}
        />
      </UserButton>
    </PageContextProvider>
  );
}
